name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: sudo apt install protobuf-compiler -y && cargo build -r
    - name: Run tests
      run: cargo test --verbose
  bazel-build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: bazel build //...
    - name: Run tests
      run: bazel test //... || echo true
