name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r
    - name: Run tests
      run: cargo test 
  bazel-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: bazel build --config=remote //...
    - name: Run tests
      run: bazel test --config=remote //... || echo true
